repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        args: 
          - --hook-config=--parallelism-ci-cpu-cores=1
      - id: terraform_validate
        args:
          - --hook-config=--parallelism-ci-cpu-cores=1
        files: ^terraform/env/

      - id: terraform_tflint
        args: 
          - --hook-config=--parallelism-ci-cpu-cores=1
        files: ^terraform/env/