services:
  app:
    build:
      context: .
      dockerfile: dockerfile.devcontainer
      args: 
        - USER=$USER
        - UID=$UID
    # network_mode: host
    extra_hosts:
      - "localhost:host-gateway"
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./:/app
  