name: build-and-deploy-lambda
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      LAMBDA_ZIP_KEY:  ${{ steps.out.outputs.lambda_zip_key }}
      LAMBDA_LAYER_ZIP_KEY: ${{ steps.out.outputs.lambda_layer_zip_key }}
    environment: develop
    steps:
      - uses: actions/checkout@v4

      # --- OIDC で AWS 認証 ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ap-northeast-1

      # Cache pip
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}

      - name: mkdir dist
        run: mkdir -p dist
      
      # --- Layer 依存インストール -------------------------
      - name: Install dependencies into layer/python
        run: |
          python -m pip install --upgrade -r requirements.txt --target ../layer
        working-directory: src

      # --- ZIP 作成 --------------------------------------
      - name: Package layer
        run: zip -r ../dist/layer.zip .
        working-directory: layer

      - name: Package lambda
        run: zip -r ../dist/lambda.zip .
        working-directory: src

      # # --- ビルド & ZIP ------------------------------
      # - name: Build layer & lambda
      #   run: |
      #     mkdir -p dist/
      #     pip install -r src/requirements.txt -t dist/
      #     zip -r layer.zip dist/
      #     zip -r lambda.zip src/


      # --- S3 へアップロード --------------------------
      - name: Upload to S3 & publish layer
        id: out
        env:
          BUCKET: aws-vpc-lambda-integration-dev
          SHA: ${{ github.sha }}
        run: |
          LAMBDA_ZIP_KEY=lambda/${SHA}.zip
          LAMBDA_LAYER_ZIP_KEY=lambda-layers/${SHA}.zip
          aws s3 cp dist/lambda.zip s3://$BUCKET/$LAMBDA_ZIP_KEY
          aws s3 cp dist/layer.zip    s3://$BUCKET/$LAMBDA_LAYER_ZIP_KEY

          echo "lambda_zip_key=$LAMBDA_ZIP_KEY"   >> "$GITHUB_OUTPUT"
          echo "lambda_layer_zip_key=$LAMBDA_LAYER_ZIP_KEY" >> "$GITHUB_OUTPUT"

  terraform:
    needs: build
    runs-on: ubuntu-latest
    environment: develop
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
    steps:
      - uses: actions/checkout@v4
      # ===== Plan & Run の作成 ===============================
      - name: Create run on HCP Terraform
        id: run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        with:
          workspace: ${{ secrets.TF_WORKSPACE }}
          message: "CI: deploy commit ${{ github.sha }}"
        env:
          TF_VAR_lambda_zip_key:  ${{ toJSON(needs.build.outputs.LAMBDA_ZIP_KEY) }}
          TF_VAR_lambda_layer_zip_key:  ${{ toJSON(needs.build.outputs.LAMBDA_LAYER_ZIP_KEY) }}

      # ===== Apply (承認後) ==================================
      - name: Apply run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        with:
          run: ${{ steps.run.outputs.run_id }}