name: build-and-deploy-lambda
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      FUNC_KEY:  ${{ steps.out.outputs.func_key }}
      LAYER_KEY: ${{ steps.out.outputs.layer_key }}
    environment: develop
    steps:
      - uses: actions/checkout@v4

      # --- OIDC で AWS 認証 ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ap-northeast-1

      # --- ビルド & ZIP ------------------------------
      - name: Build layer & function
        run: |
          mkdir -p dist
          pip install -r src/requirements.txt -t layer/python
          zip -r dist/layer.zip layer
          zip -r dist/function.zip src

      # --- S3 へアップロード --------------------------
      - name: Upload to S3 & publish layer
        id: out
        env:
          BUCKET: aws-vpc-lambda-integration-dev
          SHA: ${{ github.sha }}
        run: |
          FUNC_KEY=lambda-functions/${SHA}.zip
          LAYER_KEY=lambda-layers/${SHA}.zip
          aws s3 cp dist/function.zip s3://$BUCKET/$FUNC_KEY
          aws s3 cp dist/layer.zip    s3://$BUCKET/$LAYER_KEY

          echo "func_key=$FUNC_KEY"   >> "$GITHUB_OUTPUT"
          echo "layer_key=$LAYER_KEY" >> "$GITHUB_OUTPUT"

  terraform:
    needs: build
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v4
      # ===== Plan & Run の作成 ===============================
      - name: Create run on HCP Terraform
        id: run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        with:
          workspace: ${{ secrets.TF_WORKSPACE }}
          message: "CI: deploy commit ${{ github.sha }}"
        env:
          TF_VAR_lambda_zip_key:  ${{ toJSON(needs.build.outputs.FUNC_KEY) }}
          TF_VAR_lambda_layer_zip_key:  ${{ toJSON(needs.build.outputs.LAYER_KEY) }}

      # ===== Apply (承認後) ==================================
      - name: Apply run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        with:
          run: ${{ steps.run.outputs.run_id }}