name: build-and-deploy-lambda
on:
  pull_request:
    branches:
      - develop
    types: [closed]

  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  validate_environment_secrets:
    uses: ./.github/workflows/validate-environment-secrets.yml
    secrets: inherit
    with:
      environment_name: develop

  build-and-push:
    needs: validate_environment_secrets
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
    
  