name: 'Reusable Workflow: Plan and Deploy with TFC'

on:
  workflow_call:
    inputs:
      LAMBDA_ZIP_KEY:
        required: false
        default: null
        type: string
      LAMBDA_LAYER_ZIP_KEY:
        required: false
        default: null
        type: string
  workflow_dispatch:

jobs:
  plan-and-apply:
    runs-on: ubuntu-latest
    environment: develop
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ secrets.TF_DEV_WORKSPACE }}
      EXISTING_AWS_S3_ARTIFACT_BUCKET_NAME: ${{ secrets.EXISTING_AWS_S3_ARTIFACT_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Create run on HCP Terraform
        id: plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        with:
          workspace: ${{ secrets.TF_DEV_WORKSPACE }}
          message: "Commit Hash: ${{ github.sha }}"
        env:
          TF_VAR_lambda_zip_key:        ${{ toJSON(inputs.LAMBDA_ZIP_KEY) }}
          TF_VAR_lambda_layer_zip_key:  ${{ toJSON(inputs.LAMBDA_LAYER_ZIP_KEY) }}
          TF_VAR_existing_artifacts_bucket_name: ${{ toJSON(env.EXISTING_AWS_S3_ARTIFACT_BUCKET_NAME) }}

      - name: Apply run
        id: apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        with:
          run: ${{ steps.plan.outputs.run_id }}
