name: 'Reusable Workflow: Build and Push Lambda'
on:
  workflow_call:
    outputs:
        LAMBDA_ZIP_KEY:
          value: ${{ jobs.build-and-push.outputs.LAMBDA_ZIP_KEY }}
        LAMBDA_LAYER_ZIP_KEY:
          value: ${{ jobs.build-and-push.outputs.LAMBDA_LAYER_ZIP_KEY }}
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      LAMBDA_ZIP_KEY:  ${{ steps.out.outputs.lambda_zip_key }}
      LAMBDA_LAYER_ZIP_KEY: ${{ steps.out.outputs.lambda_layer_zip_key }}
    environment: develop
    steps:
      - uses: actions/checkout@v4

      # --- OIDC で AWS 認証 ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Cache pip
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}

      - name: mkdir dist
        run: mkdir -p dist
      
      # --- Layer 依存インストール -------------------------
      - name: Install dependencies into layer/python
        run: |
          python -m pip install --upgrade -r requirements.txt --target ../layer
        working-directory: src

      # --- ZIP 作成 --------------------------------------
      - name: Package layer
        run: zip -r ../dist/layer.zip .
        working-directory: layer

      - name: Package lambda
        run: zip -r ../dist/lambda.zip .
        working-directory: src

      # --- S3 へアップロード --------------------
      - name: Upload to S3 & publish layer
        id: out
        env:
          BUCKET: ${{secrets.AWS_S3_ARTIFACT_BUCKET_NAME}}
          SHA: ${{ github.sha }}
        run: |
          LAMBDA_ZIP_KEY=lambda/${SHA}.zip
          LAMBDA_LAYER_ZIP_KEY=lambda-layers/${SHA}.zip
          aws s3 cp dist/lambda.zip s3://$BUCKET/$LAMBDA_ZIP_KEY
          aws s3 cp dist/layer.zip    s3://$BUCKET/$LAMBDA_LAYER_ZIP_KEY

          echo "lambda_zip_key=$LAMBDA_ZIP_KEY"   >> "$GITHUB_OUTPUT"
          echo "lambda_layer_zip_key=$LAMBDA_LAYER_ZIP_KEY" >> "$GITHUB_OUTPUT"
