name: 'Reusable Workflow: Validate Environment Secrets'

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
        AWS_DEFAULT_REGION:
            required: true
            description: 'Default AWS region for the workflow.'
        AWS_ASSUME_ROLE_ARN:
            required: true
            description: 'The ARN of the role to assume for AWS actions.'
        TF_API_TOKEN:
            required: true
            description: 'Terraform API token for authentication.'
        TF_CLOUD_ORGANIZATION:
            required: true
            description: 'Terraform Cloud organization name.'
        TF_WORKSPACE:
            required: true
            description: 'Terraform Cloud workspace name.'

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    name: Validate Secrets
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Validate required environment secrets
        run: |
          echo "✅ All required environment secrets are set and valid."
